package dev.ifrs;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

// Generated by Selenium IDE
public class IfrsTest {
  private static WebDriver driver; // Colocado na mão como static/estático, por determinação do JUnit5, pra não dar erro
  private static Map<String, Object> vars; // Colocado como static (idem acima)
  static JavascriptExecutor js; // Colocado como static (idem acima)

  @BeforeAll
  public static void setUp() { // Colocado como static (idem acima)
    driver = new FirefoxDriver();
    // driver = new ChromeDriver(); // Só funciona até a versão 107 do Chrome.
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterAll
  public static void tearDown() { // Colocado como static (idem acima)
    driver.quit();
  }
  @Test
  public void ifrs() {
    driver.get("http://poa.ifrs.edu.br/");
    driver.manage().window().setSize(new Dimension(1920, 1020));
    driver.findElement(By.cssSelector(".item-124 img")).click();
    driver.findElement(By.cssSelector(".item-839 img")).click();
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.cssSelector(".select2-selection__placeholder")).click();
    driver.findElement(By.cssSelector(".select2-search__field")).sendKeys("porto alegre");
    driver.findElement(By.cssSelector(".select2-search__field")).sendKeys(Keys.ENTER);
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".col-lg-4:nth-child(1) .card-title"));
      assert(elements.size() > 0);
    }
  }
}
